### ISSUE TITLE
Translate CardinalKit to Spanish [Useful for developers in Spain & Latam]

### ISSUE THREAD

**Issue by miscaminatas** [CardinalKit/CardinalKit#109]
Translate CardinalKit in multiples languages.
Starting a test by Spanish.

1.- Save time and money to developers. Improve time to implementation.
2.- Translate recognized medical surveys for use with CardinalKit.
3.- Extend Translates to Partner Projects.

**CardinalKit**

Useful for hispanic or latino population in US [For Example: Florida State]
Useful for hispanic or latino population Spain & LatAm.

More Studies: Track- Surveys - FollowUp

https://www.miscaminatas.com/index.html

**Goals**

1.- WHO Global action plan on physical activity 2018–2030 "More active people for a healthier world"
2.- Non-communicable disease (NCD) https://www.cdc.gov/globalhealth/healthprotection/ncd/about.html

**Comment by vishnuravi** [comment]
Thank you for the suggestion, @miscaminatas, we would love to do this! Our new CardinalKit framework, launching in Early 2023, will have enhanced capabilities for localization. cc: @PSchmiedmayer
