### ISSUE TITLE
[feature-request] Support for Apple Health Records

### ISSUE THREAD

**Issue by ssgutierrez42** [CardinalKit/CardinalKit#12]
**Describe the solution you'd like**

Use Apple's FHIR models to fetch and store data from health records onto:
- Firestore,
- Google's Smart on FHIR.

https://github.com/apple/FHIRModels

**NOTE: interest on features is gaged using reactions on this first post: e.g.  👍**

**Comment by ssgutierrez42** [comment]
Documentation on accessing Apple's Health Records:
https://developer.apple.com/documentation/healthkit/samples/accessing_health_records

Note that the iOS simulator has sample health record information that you can spoof and use.

**Comment by vishnuravi** [comment]
Completed in #44
