### ISSUE TITLE
[feature-request] Add Covid-19 survey into core codebase

### ISSUE THREAD

**Issue by mhittle** [CardinalKit/CardinalKit#13]
Add the survey below: 

https://bphc.hrsa.gov/emergency-response/covid-19-survey-tools-questions

Implement some common medical surveys into CardinalKit that our teams can use as-is, or modify freely.

See StudyTasks.swift

**NOTE: interest on features is gaged using reactions on this first post: e.g.  👍**

**Comment by vishnuravi** [comment]
Templated surveys are now available in our ResearchKitOnFHIR library: https://github.com/StanfordBDHG/ResearchKitOnFHIR
