### ISSUE TITLE
Github action builds are taking too long

### ISSUE THREAD

**Issue by vishnuravi** [CardinalKit/CardinalKit#135]
Builds are taking between 30-45 minutes, with a large portion involving installing Pods. Perhaps a cache mechanism should be used?

**Comment by PSchmiedmayer** [comment]
#108 introduces a basic caching mechanism for CocoaPods and Swift Package dependencies to address this issue. The caching mechanism caches the CocoaPods dependencies using the [actions/cache](https://github.com/actions/cache) GitHub actions. Unfortunately, adding [fastlane](https://fastlane.tools) to automate the build adds a small overhead that reduces the advancements of the better caching of dependencies. 

A long-term solution would be to rely on self-hosted runners that provide way better performance than the GitHub runners that we currently use. GitHub promised to deliver self-hosted runners last quarter (https://github.com/github/roadmap/issues/507), so I hope that they are available very soon. 
Most of the time is spent building the dependencies and a small portion on the project itself. A more aggressive build cache for the dependencies might also be an option that we could consider.
