### ISSUE TITLE
[feature-request] Build post-processing and FireStore / Cloud Storage schema/pipeline for Range of Motion Active Task 

### ISSUE THREAD

**Issue by mhittle** [CardinalKit/CardinalKit#14]
We can currently launch a the Range of Motion Active Task from ResearchKit, but we don't have a way to process/store the data. 

Build out a pipeline for these data once they've been collected from the device. 

http://researchkit.org/docs/docs/ActiveTasks/ActiveTasks.html#range

**NOTE: interest on features is gaged using reactions on this first post: e.g.  👍**

**Comment by ssgutierrez42** [comment]
In CardinalKit project, see `StudyTableViewController+CardinalKit.swift` for Cloud Storage inspiration (as of Sep 10th, 2020). 
Solution should extend to other active tasks as well.
