### ISSUE TITLE
[feature-request] Question type that asks a question based on a previous survey response

### ISSUE THREAD

**Issue by sujaan13** [CardinalKit/CardinalKit#143]
**Is your feature request related to a problem? Please describe.**
The problem we are trying to solve is related to asking users followup questions based on their past responses in the current survey, or past responses of a different survey. Additionally, we would like to ask users if they have taken corrective action, if they have answered a question with a specific response using scheduled surveys.

**Describe the solution you'd like**
The solution I envision is to add two additional questionTypes to the Cardinal Kit web dashboard. One type of question that will query the results of another survey, and ask a question based on the result. A second type of question that is an if statement that ask question based on a previous question in the same survey.

**Describe alternatives you've considered**
I was able to achieve this functionality by querying survey results inside the cardinalkit ios app, however, this would require hardcoding surveys workflows into the ios app, and it seems like a cleaner solution to schedule surverys using cloud surveys functionality.

**Comment by vishnuravi** [comment]
Hi @sujaan13 thank you for this great suggestion! While this is out of scope for further enhancements to the current framework, it is a feature we can look into adding to the [upcoming redesigned framework](https://github.com/StanfordBDHG/CardinalKit) - cc: @PSchmiedmayer.
