### ISSUE TITLE
[feature-request] Deploy to TestFlight

### ISSUE THREAD

**Issue by varunshenoy** [CardinalKit/CardinalKit#15]
**Is your feature request related to a problem? Please describe.**
The CardinalKit example app is constantly updated with new contributions and features. 
What is a quick way to build the latest version and get it running on test devices? 

**Describe the solution you'd like**
With every update to `master`, create and deploy a TestFlight app.

Leverage any CI/CD integration. Please communicate with the CK team to define which Apple Developer account can be used. 

**NOTE: interest on features is gaged using reactions on this first post: e.g.  👍**

**Comment by vishnuravi** [comment]
Thank you @PSchmiedmayer for setting this up!
