### ISSUE TITLE
in application error message: Unable to Login Please try again in 5 minutes.

### ISSUE THREAD

**Issue by mikephelan** [CardinalKit/CardinalKit#19]
**Describe the bug**
System information:
MacOS Catalina, v10.15.4
Git 2.24.1
XCode 11.6
Swift 5.2

Goal: Installation and run of CardinalKit-Example, with back-end data store connectivity

Details of error:
In-application error:
Unable to Login Please try again in 5 minutes.
XCode console error:
Domain not whitelisted by project
2020-09-04 17:16:29.906003-0400 CardinalKit Example[42808:383324] Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
2020-09-04 17:16:29.959844-0400 CardinalKit Example[42808:383324] Could not signal service com.apple.WebKit.Networking: 113: Could not find specified service

**To Reproduce**
1. Follow these instructions:
https://cardinalkit.org/docs/getting_started
https://cardinalkit.org/docs/setup_cloud

**Expected behavior**
A running instance of CardinalKit-Example in the iPhone simulator of XCode, which uploads completed survey records to a Firebase Cloud FireStore NoSQL database

**Smartphone (please complete the following information):**
 - Device: iPhone SE Second Generation (simulator)

**Additional context**
Preparation for this hackathon:
https://biodesign.stanford.edu/news---events/virtual-buildathon.html

**Comment by mikephelan** [comment]
This is how I was able to make the CardinalKit-Application application function, with back-end connectivity.

Set up your Firebase environment as specified here:
https://cardinalkit.org/docs/setup_cloud
Note that the database type is now rebranded as Cloud FireStore
Note the local filesystem location to which you download the file, GoogleServices-Info.plist (you need it to configure the application prior to launching the application in XCode)

On the local filesystem:
git clone https://github.com/CardinalKit/CardinalKit.git
cd CardinalKit/CardinalKit-Example
git checkout remotes/origin/swiftui
pod install
cp <path-to>/GoogleService-Info.plist <path-to>/CardinalKit/CardinalKit-Example/CardinalKit/Supporting\ Files/GoogleService-Info.plist

In the MacOS Finder:
Launch XCode via <path-to>/CardinalKit/CardinalKit-Example/CardinalKit.xcworkspace

In XCode:
Product > Build for Running
Product > Run
in iPhone4 simulator
choose default buttons, enter your email and a new made-up password
for the passcode, define it using the numerical keys on the keyboard
This ends and then you run again, this time your entered credentials from the last run are accepted.
Run through answering the real survey questions, including things like, how is your health on a scale of 1 - 5?
Eventually you finish.
Once finished, access the record in Firebase

In the browser:
Access the Firebase console
From left-hand menu, Develop, Cloud Firestore
in canvas, choose Data tab
choose Surveys, then Survey Task, choosing the only listed item in each of the columns
Eventually you get to a long rendered node list in the right-most panel
That node list is the record from the survey you completed in the app

In subsequent runs of the iPhone application on the XCode simulator, you will no longer be challenged for authentication. Instead, you will be presented with a CardinalKit Sample App splash page. That spash page will feature two items, Survey Sample and Active Task Sample. Choosing Survey Sample will allow you to perform additional submissions to the survey application.

**Comment by varunshenoy** [comment]
Thanks for your detailed notes!
