### ISSUE TITLE
[feature-request] Convert "Studies" tab Interface to SwiftUI

### ISSUE THREAD

**Issue by ssgutierrez42** [CardinalKit/CardinalKit#2]
**Describe the solution you'd like**

Update the primary navigation list of the CardinalKit sample to leverage the flexible features of SwiftUI. 

Use tutorial https://developer.apple.com/tutorials/swiftui/building-lists-and-navigation#Get-to-Know-the-Sample-Data as reference. 

Create a sample Resource file such the `landmarkData.json` file seen above. Use hard-coded data for now. 

A next step will be to grab this resource and populate it from server data (Firestore).

**NOTE: interest on features is gaged using reactions on this first post: e.g.  👍**

**Comment by varunshenoy** [comment]
@all-contributors please add @ssgutierrez42 for code

**Comment by varunshenoy** [comment]
@all-contributors please add @varunshenoy for code and maintenance. Also add @ssgutierrez42 for maintenance.

**Comment by varunshenoy** [comment]
@all-contribbutors please add @varunshenoy for code

**Comment by varunshenoy** [comment]
@all-contributors please add @varunshenoy for code

**Comment by vishnuravi** [comment]
This feature has been added!
