### ISSUE TITLE
Community Recognition 🎉

### ISSUE THREAD

**Issue by varunshenoy** [CardinalKit/CardinalKit#22]
Want to recognize someone in the community? Let us know and we'll add them to the [README.md](https://github.com/CardinalKit/CardinalKit)!

**Comment by varunshenoy** [comment]
@all-contributors please add @mhittle for ideas, maintenance, and projectManagement.

**Comment by varunshenoy** [comment]
@all-contributors please add @aamirrasheed for content and video.

**Comment by vishnuravi** [comment]
@all-contributors please add @vishnuravi for code

**Comment by vishnuravi** [comment]
@all-contributors please add @PSchmiedmayer for code
