### ISSUE TITLE
[feature-request] Data Visualization for Patients

### ISSUE THREAD

**Issue by varunshenoy** [CardinalKit/CardinalKit#23]
**Is your feature request related to a problem? Please describe.**
Add a new section to the Studies view to include a third tab for data visualization. For bonus points: add hooks to the `CKConfiguration.plist` file to customize the data visualization.

**Describe the solution you'd like**
For every important quantitative survey, show some chart (bar, line, etc.) to go with it. It should read from Firebase and there should be an easy way to export the graphs as a PDF.

**Additional context**
This could also be a great place to provide advice and personalized "cards" to help patients understand what their data means.

**NOTE: interest on features is gaged using reactions on this first post: e.g.  👍**

**Comment by mster** [comment]
My team would like to plan on tackling this issue for the CardinalKit buildathon.

**Comment by ssgutierrez42** [comment]
Leaving a comment here as a note for inspiration -- 
Both CareKit and ResearchKit provide graphing APIs that may be of interest. 

https://developer.apple.com/design/human-interface-guidelines/carekit/overview/views/
https://developer.apple.com/documentation/carekit/chart_interfaces

http://researchkit.org/docs/docs/ChartsAndGraphs/ChartsAndGraphs.html

**Comment by mster** [comment]
@ssgutierrez42 my hero!

**Comment by mster** [comment]
I have been looking through the codebase and wanted to circle back before my team and I begin. 

For adding visualizations to the Studies View, it seems as though we'll want to work with/hook into the Studies Component here: https://github.com/CardinalKit/CardinalKit/tree/swiftui/CardinalKit-Example/CardinalKit/Components/Study

It just seems weird to be to be adding features to an "Example" application. Is this the right direction? Looking to get some sign-off or recommendation before we move forward. @ssgutierrez42 @varunshenoy 

Thanks again! 😸

**Comment by varunshenoy** [comment]
@mster That's exactly right — the example app is where any future developers will start from. 

The visualization code would likely connected into the StudiesUI we currently have: https://github.com/CardinalKit/CardinalKit/blob/swiftui/CardinalKit-Example/CardinalKit/Components/User%20Interface/StudiesUI.swift

**Comment by mster** [comment]
@varunshenoy Great to hear. We'll get started and refer back here with any issues!
