### ISSUE TITLE
[feature-request] email signed consent to patient after sign-up

### ISSUE THREAD

**Issue by ssgutierrez42** [CardinalKit/CardinalKit#27]
**Is your feature request related to a problem? Please describe.**
CardinalKit projects make use of ResearchKit to prompt patients for medical consent:
https://user-images.githubusercontent.com/5482213/92849813-964a7380-f3a0-11ea-8436-c1388236a956.png

This feature request is to enable the delivery of the signed consent document via email directly to the patient. 📩

**Describe the solution you'd like**
The signed consent is already stored as a PDF on device right after the user fills it out (you can pull it up in the Profile tab).

You may also want to leverage Google Cloud Functions
https://cloud.google.com/functions/

^ &, if you do, some kind of email delivery solution
https://nodemailer.com/about/

**NOTE: interest on features is gaged using reactions on this first post: e.g.  👍**

**Comment by patrikkei** [comment]
Hello, i would like to work on this issue if is posible :)
