### ISSUE TITLE
[feature-request] Populate "Studies" tab from server (Firestore) data.

### ISSUE THREAD

**Issue by ssgutierrez42** [CardinalKit/CardinalKit#3]
**Describe the solution you'd like**

Fetch the solution from Issue #2 and populate the project's activity rows from Firestore.

Update our CardinalKit documentation to instruct on how-to create entries on Firestore that each app can read. 

Provide a data source that CardinalKit teams can automatically import to Firebase. 

**NOTE: interest on features is gaged using reactions on this first post: e.g.  👍**

**Comment by vishnuravi** [comment]
Completed in v2.
