### ISSUE TITLE
Rename base branch from 'master' to 'main'

### ISSUE THREAD

**Issue by sgrinich** [CardinalKit/CardinalKit#30]
**Is your feature request related to a problem? Please describe.**

The 'master' branch is a reference to master/slave terminology in computer science. It is not appropriate to continue using this term. 

**Describe the solution you'd like**
The new industry standard is `main`. 

**Additional context**

https://www.cnet.com/news/twitter-engineers-replace-racially-loaded-tech-terms-like-master-slave/

**Comment by varunshenoy** [comment]
@sgrinich Thanks for this recommendation, we completely agree. We need to confirm that nothing will break on our local end (i.e. documentation, etc.) and we'll go ahead with the name change right after the buildathon this weekend.
