### ISSUE TITLE
[feature-request] Create a CardinalKit-owned production ready GCP instance.

### ISSUE THREAD

**Issue by ssgutierrez42** [CardinalKit/CardinalKit#4]
**Describe the solution you'd like**

Create procedure to allow other CardinalKit teams to use our GCP instance as a fallback. 

In addition to that, create and define a Firestore ruleset in conjunction to SOM RIT that enforces the patterned use of the `authCollection` in the CardinalKit sample projects. 

**NOTE: interest on features is gaged using reactions on this first post: e.g.  👍**

**Comment by vishnuravi** [comment]
Addressed by #145.
