### ISSUE TITLE
Unwanted pods folder in Example project 

### ISSUE THREAD

**Issue by prabakarviji** [CardinalKit/CardinalKit#42]
**Describe the bug**
Unwanted pods folder in Example project that leads to more space in the project

**To Reproduce**
1. Go to CardinalKit-Example
2. Click on Pods to see all pods that can be installed on local using `pod install`

**Expected behavior**
Pod folder must be added to `.gitignore` to avoid

**Comment by vishnuravi** [comment]
Thanks for the suggestion! This issue has been addressed in #68.
