### ISSUE TITLE
[feature-request] Create a production ready CardinalKit web portal.

### ISSUE THREAD

**Issue by ssgutierrez42** [CardinalKit/CardinalKit#5]
**Describe the solution you'd like**
Must make use of #4 (including rule-sets).

Create a ReactJS-powered production ready CardinalKit web portal. 

Here are some key features we're looking for:
- It should be easy to set up (i.e. the only parts a potential team should worry about are replacing Firebase credentials and hosting the portal).
- Two-factor authentication for access to data in portal (required for HIPAA compliance).
- It should provide easy access to survey data.
- Show the user customizable ways to visualize the survey data.
- All survey consent forms can be aggregated into Firebase Storage from the app so clinicians can view them from the portal.
- (nice to have) CRUD operations on the database through the portal (no need to ever touch the Firebase database through their website anymore!)
- (nice to have) Customize user interface colors to match project.
- (nice to have) Easy to understand documentation for customizing/setting up the portal.

See https://github.com/cs342/CardinalKit-CS342-Web
as an example! 

**NOTE: interest on features is gaged using reactions on this first post: e.g.  👍**

**Comment by sivakb** [comment]
Hi @varunshenoy  & @ssgutierrez42 

I am interested in contributing to this feature. I need a few clarifications on this, can we connect on call to discuss this?

**Comment by ssgutierrez42** [comment]
Hi @sivakb!

Are you available next Friday @ 2PM to connect (Sep 25th)? would love to chat!

**Comment by sivakb** [comment]
@ssgutierrez42  Yes,I am available on Sep 25th. This is my email address siva.kb@spritle.com. Looking forward to meet you.

**Comment by vishnuravi** [comment]
This is being addressed at: https://github.com/CardinalKit/CardinalKit-Web-Dashboard
