### ISSUE TITLE
[feature-request] Android version of CardinalKit

### ISSUE THREAD

**Issue by mhittle** [CardinalKit/CardinalKit#6]
**Describe the solution you'd like**

Create a GCP-enabled Android app.

Leverage the Firebase SDK to accomplish login:
https://firebase.google.com/docs/auth

You may want to leverage http://researchstack.org/ (as an alternative to ResearchKit)
to create surveys and a consent process.

**NOTE: interest on features is gaged using reactions on this first post: e.g.  👍**

**Comment by vishnuravi** [comment]
Development underway at https://github.com/CardinalKit/CardinalKit-Android
