### ISSUE TITLE
[feature-request] Template 25+ most common medical surveys with ResearchKit

### ISSUE THREAD

**Issue by ssgutierrez42** [CardinalKit/CardinalKit#7]
**Describe the solution you'd like**

Implement some common medical surveys into CardinalKit that our teams can use as-is, or modify freely.

See `StudyTasks.swift`

**NOTE: interest on features is gaged using reactions on this first post: e.g.  👍**

**Comment by mster** [comment]
I'm interesting in contributing. Would this be a `good-first-issue`?

**Comment by varunshenoy** [comment]
Absolutely — create a fork of the project, add in common medical surveys, and submit a pull request. We're excited for your commit! If you need anything, you can leave a question here.

**Comment by mikephelan** [comment]
Is [this](https://www.surveymonkey.com/mp/medical-research-surveys/) a reasonable starting point for examples of common medical surveys?
See "Easy Ways to Conduct Medical Surveys" towards the bottom of the page.

**Comment by varunshenoy** [comment]
That seems great — there is also many more examples [here](https://www.physio-pedia.com/Category:Outcome_Measures) with specific research-oriented names (i.e. P4, SF34, etc.).

**Comment by ssgutierrez42** [comment]
Linking a prior feature-request to add a COVID-19 data collection tool as a survey:
https://github.com/CardinalKit/CardinalKit/issues/13

**Comment by vishnuravi** [comment]
We are now providing templated medical surveys in our ResearchKitOnFHIR library, which can be used with CardinalKit applications: https://github.com/StanfordBDHG/ResearchKitOnFHIR
